### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Nickyg001** [veritas501/Potplayer-Subtitle-Translate-GoogleFix#1]
I have tried your POTPLAYER script and I find it FANTASTIC !!! but above all functional.

I was wondering, is it possible somehow to do the same thing, to develop a translation script for the VLC-PLAYER software that is most commonly used ??

**Comment by veritas501** [comment]
Sorry, this is not in plan.

**Comment by Nickyg001** [comment]
:'(
