### ISSUE TITLE
非常感谢，受惠已久。弱弱问句，如何导出翻译后字幕或一键保存为双语字幕文件

### ISSUE THREAD

**Issue by xoxlll** [veritas501/Potplayer-Subtitle-Translate-GoogleFix#12]
如题。感谢

**Comment by veritas501** [comment]
呃 这个确实不太清楚啊（挠头），感觉这不是翻译插件干的事情，得看potplayer自身有没有这种功能了。

**Comment by xoxlll** [comment]
还是非常感谢。今天更新的版本已增加翻译字幕保存。：）

**Comment by Copy2Translator** [comment]
> 还是非常感谢。今天更新的版本已增加翻译字幕保存。：）
你好，我最新版 potplayer 也勾选了保存字幕时同时保存翻译，但是保存出来的字幕文件乱码，搜了一圈没有找到解决办法，能说说你的解决方法吗？谢谢！~

**Comment by Copy2Translator** [comment]
找到设置了，在保存字幕界面那里有个编码，把默认的 ANSI 改成 UTF-8 然后保存就能正常显示中文了！
