### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by hamed3949** [veritas501/Potplayer-Subtitle-Translate-GoogleFix#3]
Hi, the translation for PotPlayer has failed 
I really need it
Please fix it
Thank you
![pot](https://user-images.githubusercontent.com/24311930/100907191-41218800-34df-11eb-8660-35a826890323.JPG)

**Comment by Witawat** [comment]
me too
not work

**Comment by veritas501** [comment]
https://github.com/veritas501/Potplayer-Subtitle-Translate-GoogleFix/blob/fix_tkk/SubtitleTranslate%20-%20googleFix.as

@Witawat @hamed3949 

Busy this days sorry :(
Not fully tested, if it works plz tell me.

**Comment by hamed3949** [comment]
@veritas501 

Hi Good day
I tried again but it does not work

**Comment by veritas501** [comment]
@hamed3949 I think the script is working now, if it still not working can you send me the video and tell me the source language and target language? thanks.

**Comment by hamed3949** [comment]
@veritas501  
Hello my friend
The problem is solved and it works well
thank you very much
